###

# curl -X POST http://localhost:8080/api/generate-content
#-H "Content-Type: application/json"
#-d '{
#   "key": "your-api-key",
#   "contents":[
#      {
#         "parts":[
#            {"text":"purpose=greeting"},
#            {"text":"category=automated_phone_message"},
#            {"text":"business=캠핑장"},
#            {"text":"type=greeting_message"},
#            {"text":"feeling=energetic"},
#            {"text":"target_audience=general_customers"},
#            {"text":"tone=informative"},
#            {"text":"language=Korean"},
#            {"text":"business_status=open"},
#            {"text":"monday_to_friday=00:00 AM - 23:59 PM"},
#            {"text":"weekends=Closed"},
#            {"text":"holidays=09:00 AM - 02:00 PM"}
#         ]
#      }
#   ],
#   "generationConfig":{
#      "temperature":0.2,
#      "topK":50,
#      "topP":1,
#      "maxOutputTokens":3000,
#      "responseMimeType":"text/plain"
#   }
#}'
POST http://localhost:8080/api/v1/gemini/question
Content-Type: application/json

{
  "model": "gemini-2.0-flash",
  "key": "AIzaSyCeX0mF6xl2SZHreHDL84LBNaM3y0YOFk4",
  "contents": [
    {
      "parts": [
        {
          "text": "purpose=greeting"
        },
        {
          "text": "category=automated_phone_message"
        },
        {
          "text": "business=캠핑장"
        },
        {
          "text": "type=greeting_message"
        },
        {
          "text": "feeling=energetic"
        },
        {
          "text": "target_audience=general_customers"
        },
        {
          "text": "tone=informative"
        },
        {
          "text": "language=Korean"
        },
        {
          "text": "business_status=open"
        },
        {
          "text": "monday_to_friday=00:00 AM - 23:59 PM"
        },
        {
          "text": "weekends=Closed"
        },
        {
          "text": "holidays=09:00 AM - 02:00 PM"
        }
      ]
    }
  ],
  "generationConfig": {
    "temperature": 0.2,
    "topK": 50,
    "topP": 1,
    "maxOutputTokens": 3000,
    "responseMimeType": "text/plain"
  }
}

###

