spring.application.name=ai_llm_module
server.port=8080
logging.level.org.springframework.cloud.openfeign=INFO
logging.level.com.kimbaro.www.ai_llm_module.domains.HELLORING_AI_TEXT=INFO
logging.level.feign.Logger=INFO
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8


